name: A Blog Site
favicon: null
layout_spectrum: 0.50095
typography_spectrum: 0.76778
title: 'Random thoughts, photos and links'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74137003-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313b21'
    - '#daa738'
    - '#bb741e'
    - '#fffeda'
    - '#0f0c13'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
