name: A Blog Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60016
title: 'Random thoughts, photos and links'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313b21'
    - '#daa738'
    - '#bb741e'
    - '#fffeda'
    - '#0f0c13'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
