name: A Blog Site
favicon: null
layout_spectrum: 0.9217985062859952
typography_spectrum: 0.9716375856660306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9234652284067124
  lightness: 0.6904621929861605
  saturation: 0.03681071288883686
  rhythmicContrast: 0.7156585063785315
purpose: []
